export const requiredUiComponents = [
  "Sidebar",
  "Header",
  "Breadcrumb",
  "PageHeader",
  "Cards",
  "MetricCards",
  "Tables",
  "Filters",
  "Search",
  "Buttons",
  "Forms",
  "Dialogs",
  "Drawers",
  "Tabs",
  "Charts",
  "Calendar",
  "Kanban",
  "Timeline",
  "AIRecommendationCard",
  "AgentStatusCard",
  "WorkflowStepper",
  "ApprovalStatusBadge",
  "PublishingStatusBadge",
  "NotificationDrawer",
  "UserProfileMenu",
  "WorkspaceSwitcher",
  "IntegrationCard",
  "EmptyState",
  "LoadingState",
  "ErrorState",
] as const;

export const statusBadges = [
  "Draft",
  "Under Review",
  "Needs Revision",
  "Approved",
  "Scheduled",
  "Published",
  "Failed",
  "Rejected",
  "Archived",
  "Running",
  "Paused",
  "Completed",
  "Warning",
  "Critical",
] as const;
