export const designTokens = {
  colors: {
    pageBackground: "#FFFFFF",
    sidebarBackground: "#FFFFFF",
    cardBackground: "#FFFFFF",
    primaryBlue: "#2563EB",
    primaryHover: "#1D4ED8",
    deepNavyText: "#0F172A",
    primaryText: "#111827",
    secondaryText: "#4B5563",
    mutedText: "#9CA3AF",
    border: "#E5E7EB",
    softBorder: "#EEF2F7",
    hoverBackground: "#F8FAFC",
    selectedBackground: "#EEF4FF",
    success: "#16A34A",
    warning: "#F59E0B",
    danger: "#DC2626",
    info: "#0284C7",
    purpleAccent: "#7C3AED",
    tealAccent: "#0D9488",
    aiGradient: "linear-gradient(135deg, #2563EB, #7C3AED)",
  },
  typography: {
    fontFamily: "Inter",
    pageTitle: { fontSize: 32, fontWeight: 700 },
    sectionTitle: { fontSize: 24, fontWeight: 600 },
    cardTitle: { fontSize: 18, fontWeight: 600 },
    body: { fontSize: 16, fontWeight: 400 },
    caption: { fontSize: 14, fontWeight: 400 },
    smallLabel: { fontSize: 12, fontWeight: 500 },
  },
  layout: {
    sidebarExpandedWidth: 280,
    sidebarCollapsedWidth: 80,
    headerHeight: 72,
    workspaceMaxWidth: 1600,
    workspacePadding: 32,
    gridColumns: 12,
    menuItemHeight: 48,
    menuItemRadius: 12,
    activeIndicatorWidth: 4,
  },
} as const;
