export const creativeLifecycle = [
  "business-objective",
  "research",
  "strategy",
  "planning",
  "content-creation",
  "creative-production",
  "review",
  "optimization",
  "publishing",
  "monitoring",
  "learning",
  "continuous-improvement",
] as const;

export const videoProductionPipeline = [
  "business-goal",
  "research",
  "audience-analysis",
  "strategy",
  "script",
  "review",
  "storyboard",
  "scene-planning",
  "asset-planning",
  "image-generation",
  "video-generation",
  "narration",
  "voice",
  "music",
  "editing",
  "branding",
  "subtitle-generation",
  "thumbnail",
  "seo",
  "platform-optimization",
  "policy-validation",
  "auto-approval",
  "scheduling",
  "publishing",
  "monitoring",
  "learning",
  "optimization",
] as const;

export const videoFormats = [
  "short-videos",
  "long-videos",
  "product-demonstrations",
  "training",
  "corporate-communication",
  "educational-content",
  "interviews",
  "webinars",
  "podcasts",
  "documentaries",
  "explainers",
  "news",
  "testimonials",
  "advertisements",
  "sales-videos",
  "customer-onboarding",
  "internal-communication",
  "executive-messages",
  "animated-videos",
  "motion-graphics",
  "screen-recordings",
  "presentation-videos",
] as const;

export const videoTemplates = [
  "talking-head",
  "corporate-presentation",
  "educational",
  "explainer",
  "product-demo",
  "news",
  "interview",
  "podcast",
  "social-media-reel",
  "youtube-tutorial",
  "marketing",
  "whiteboard",
  "infographic",
  "slideshow",
  "animated-presentation",
  "event-promotion",
  "company-introduction",
  "training-module",
] as const;

export const creativePublishingChannels = [
  "linkedin",
  "facebook",
  "instagram",
  "threads",
  "x",
  "tiktok",
  "youtube",
  "website",
  "blog",
  "email-newsletter",
  "podcast-platforms",
  "internal-portals",
  "future-integrations",
] as const;

export const creativeAgents = [
  "creative-director-agent",
  "business-strategy-agent",
  "script-agent",
  "research-agent",
  "trend-agent",
  "planning-agent",
  "content-agent",
  "script-writer-agent",
  "storyboard-agent",
  "scene-agent",
  "scene-director-agent",
  "visual-designer-agent",
  "image-agent",
  "video-agent",
  "voice-agent",
  "audio-agent",
  "music-agent",
  "animation-agent",
  "subtitle-agent",
  "thumbnail-agent",
  "seo-agent",
  "compliance-agent",
  "brand-agent",
  "publishing-agent",
  "analytics-agent",
  "learning-agent",
  "creative-learning-agent",
  "knowledge-agent",
  "workflow-agent",
  "quality-assurance-agent",
  "creative-qa-agent",
  "executive-agent",
] as const;

export const creativeDecisionDimensions = [
  "brandFit",
  "brandAlignment",
  "businessAlignment",
  "compliance",
  "quality",
  "risk",
  "platformSuitability",
  "audienceFit",
  "predictedEngagement",
  "predictedRoi",
  "confidence",
  "historicalSuccess",
  "duplicateDetection",
  "trendAlignment",
  "publishingWindow",
] as const;

export const creativeMemoryDomains = [
  "audience",
  "brand",
  "visual-identity",
  "writing-style",
  "voice",
  "successful-campaigns",
  "failed-campaigns",
  "preferred-colors",
  "preferred-layouts",
  "preferred-music",
  "preferred-thumbnails",
  "previous-productions",
  "uploaded-assets",
  "business-knowledge",
] as const;

export const creativeTechnicalCapabilities = [
  "native-intelligence-runtime",
  "internal-engine-versioning",
  "capability-registry",
  "distributed-rendering",
  "background-processing",
  "job-queues",
  "parallel-production",
  "asset-caching",
  "version-control",
  "gpu-acceleration",
  "cloud-rendering",
  "high-availability",
  "scalable-storage",
  "enterprise-security",
  "audit-logging",
  "full-api-support",
  "microservice-ready-architecture",
  "plugin-architecture",
] as const;

export type CreativeLifecycleStep = (typeof creativeLifecycle)[number];
export type VideoProductionPipelineStep = (typeof videoProductionPipeline)[number];
export type CreativeAgentKey = (typeof creativeAgents)[number];
export type CreativeDecisionDimension = (typeof creativeDecisionDimensions)[number];
export type CreativeDecisionScores = Record<CreativeDecisionDimension, number>;
