export const brandAssetTypes = [
  "logos",
  "fonts",
  "brand-colors",
  "icons",
  "images",
  "videos",
  "templates",
  "music",
  "voice-profiles",
  "animations",
  "transitions",
  "documents",
  "brand-guidelines",
  "reusable-assets",
  "version-history",
] as const;

export const creativeTemplateCategories = [
  "marketing",
  "sales",
  "education",
  "corporate",
  "events",
  "hr",
  "recruitment",
  "training",
  "product-launch",
  "customer-success",
  "social-media",
  "email",
  "video",
  "presentation",
  "documents",
] as const;
