export const creativeDashboardMetrics = [
  "creativePipeline",
  "runningProductions",
  "upcomingProductions",
  "publishedProductions",
  "creativeHealth",
  "brandConsistency",
  "productionQueue",
  "aiRecommendations",
  "trendingOpportunities",
  "campaignStatus",
  "platformStatus",
  "agentStatus",
  "learningInsights",
  "storageUsage",
  "renderQueue",
  "processingQueue",
  "projectProgress",
  "recentActivities",
  "performanceKpis",
] as const;
