export const creativeStudioIntegrations = {
  dashboard: [
    "running-productions",
    "creative-kpis",
    "publishing-queue",
    "production-health",
    "active-creative-agents",
    "creative-recommendations",
    "pending-render-jobs",
    "recent-productions",
    "learning-insights",
    "campaign-performance",
  ],
  workspace: ["workspace", "brand", "campaign", "project", "creative-production"],
  brandManager: [
    "brand-voice",
    "brand-guidelines",
    "fonts",
    "colours",
    "logos",
    "products",
    "services",
    "audience",
    "messaging",
    "keywords",
    "case-studies",
    "content-pillars",
    "business-objectives",
  ],
  contentPlatform: [
    "content-library",
    "templates",
    "publishing-queue",
    "content-calendar",
    "content-generator",
    "ai-reviewer",
    "content-history",
  ],
  researchCenter: [
    "topic-research",
    "competitor-research",
    "trend-discovery",
    "keyword-research",
    "industry-insights",
    "audience-research",
    "news-monitoring",
    "research-library",
  ],
  campaignManager: ["campaign", "goals", "timeline", "audience", "kpis", "deliverables", "performance"],
  approvalCenter: ["ai-review", "policy-validation", "decision-engine", "auto-approval", "publishing"],
  socialPublishing: [
    "linkedin",
    "facebook",
    "instagram",
    "threads",
    "x",
    "youtube",
    "tiktok",
    "blog",
    "email-newsletter",
    "aspect-ratio",
    "length",
    "metadata",
    "hashtags",
    "cta",
    "thumbnail",
    "captions",
  ],
  knowledgeBase: [
    "documents",
    "previous-campaigns",
    "brand-memory",
    "content-memory",
    "approved-phrases",
    "business-profile",
    "product-knowledge",
  ],
  workflowEngine: [
    "workflow-builder",
    "automation-rules",
    "execution-history",
    "version-control",
    "audit-trail",
    "notifications",
    "scheduling",
    "task-management",
  ],
  analyticsCenter: [
    "content-analytics",
    "campaign-analytics",
    "audience-analytics",
    "platform-analytics",
    "performance-dashboard",
    "ai-recommendations",
    "learning-engine",
  ],
} as const;
