export const contentStudioCapabilities = [
  "topic-generation",
  "content-planning",
  "blog-writing",
  "linkedin-writing",
  "facebook-writing",
  "instagram-writing",
  "twitter-x-writing",
  "email-writing",
  "newsletter-writing",
  "landing-page-writing",
  "product-descriptions",
  "case-studies",
  "whitepapers",
  "reports",
  "books",
  "technical-documentation",
  "sales-copy",
  "marketing-copy",
  "seo-optimization",
  "content-repurposing",
  "translation",
  "localization",
  "content-scoring",
  "brand-consistency",
  "content-archive",
] as const;

export const imageStudioCapabilities = [
  "text-to-image",
  "image-enhancement",
  "image-editing",
  "background-removal",
  "brand-overlays",
  "poster-generation",
  "social-media-graphics",
  "banner-generation",
  "infographics",
  "illustrations",
  "marketing-creatives",
  "product-mockups",
  "thumbnail-generation",
  "presentation-graphics",
  "ai-image-upscaling",
  "style-transfer",
  "image-library",
  "version-history",
] as const;

export const audioStudioCapabilities = [
  "voice-generation",
  "authorized-voice-cloning",
  "background-music",
  "music-generation",
  "audio-enhancement",
  "noise-reduction",
  "speech-synthesis",
  "speech-recognition",
  "podcast-editing",
  "audio-branding",
  "sound-effects",
  "audio-library",
  "mixing",
  "mastering",
  "export",
] as const;

export const designStudioCapabilities = [
  "logos",
  "brand-identity",
  "social-media-graphics",
  "icons",
  "banners",
  "business-cards",
  "flyers",
  "brochures",
  "packaging",
  "marketing-materials",
  "campaign-creatives",
  "presentation-graphics",
  "email-graphics",
  "web-graphics",
] as const;
